### ISSUE TITLE
Error in Readme about virtiofs

### ISSUE THREAD

**Issue by navycatt** [wimpysworld/quickemu#187]
But quickemu does not support virtiofs, 9p only.
https://github.com/wimpysworld/quickemu/blob/7ac2768784d68a4542c4767265265c4e5d56280d/README.md?plain=1#L600
I added virtiofs support in my fork of quickemu:
https://github.com/navycatt/quickemu/blob/0f4c3f2cf45e9c96191f1829058ccebb10f20984/quickemu#L756

**Comment by ymauray** [comment]
It looks to me that this should be a pull request, and not an issue.

**Comment by ymauray** [comment]
It looks to me like this should also be a pull request.

And - again - could you flesh out your issues a bit more ? Thanks.

**Comment by navycatt** [comment]
We have a proverb:
Brevity is the sister of talent. Thanks.

**Comment by flexiondotorg** [comment]
The links you highlighted are reference material. It is not an error 🙂

Quickemu deliberately uses 9P because it doesn't require any additional services or elevated permissions. Samba is available for people wanting/needing something more robust or faster than 9P. I don't plan on adding VirtIO FS support to Quickemu as there are several options already available in Quickemu:

  * SSH
  * SPICE Webdav
  * VirtIO 9P
  * Samba
