### ISSUE TITLE
Add option to adjust vram

### ISSUE THREAD

**Issue by Slaviusz** [wimpysworld/quickemu#211]
#### Expected behaviour

Set display resolution to 4k on macos monterey

#### Actual behaviour

In macos monterey it is not possible to set display resolution higher than 2560x1440 as VRAM shows only 14MB

#### Steps to reproduce the behaviour

Create vm macos monterey
Go to system preferences -> Display
List custom resultions -> highest is 2560x1440

#### Quickemu output

--Not related--

#### Linux Distribution & Kernel

Run the following and paste the output.

```
$ uname -a
Linux gentoo 5.15.1-tkg-cacule-llvm #1 TKG SMP PREEMPT Sun Nov 7 17:03:18 CET 2021 x86_64 AMD Ryzen 7 3800X 8-Core Processor AuthenticAMD GNU/Linux

$ EIX_LIMIT=0 eix -c --installed | grep -iE "(spice|qemu|libvirt)"
[I] acct-group/qemu (0-r1@11/07/2021): System group: qemu
[I] acct-user/qemu (0-r1@11/07/2021): System user: qemu
[I] app-emulation/libvirt (7.8.0(0/7.8.0)@11/07/2021): C toolkit to manipulate virtual machines
[I] app-emulation/qemu (6.0.1-r1@11/07/2021): QEMU + Kernel-based Virtual Machine userland tools
[I] app-emulation/spice (0.15.0@11/07/2021): SPICE server
[I] app-emulation/spice-protocol (0.14.3@11/07/2021): Headers defining the SPICE protocol
[I] media-libs/virglrenderer (0.9.1@11/07/2021): library used implement a virtual 3D GPU used by qemu
[I] net-misc/spice-gtk (0.39-r1@11/07/2021): Set of GObject and Gtk objects for connecting to Spice servers and a client GUI
[I] net-misc/vde (2.3.2-r6@11/07/2021): Virtual distributed ethernet emulator for emulators like qemu, bochs, and uml
```

**Comment by flexiondotorg** [comment]
I think a good place to start with this issue is allocate a sensible amount of VRAM by default. Here are the video RAM properties that each of the display device support:

  * `vram_size_mb=<uint32>`: Exposed to ati-vga, cirrus-vga, qxl, qxl-vga, VGA
  * `vgamem=<size>        `: Exposed to bochs-display (but not currently used by Quickemu.

virtio-vga and virtio-gpu do not have any VRAM tunables.

Quickemu does attempt to allocate 128MB VRAM by default, but the display device coverage is lacking so macOS doesn't get that uplifted VRAM allocation.

**Comment by flexiondotorg** [comment]
I've made sure `vram_size_mb` and `vgamem` are appropriately configure to allocate 128MB VRAM. macOS still only reports 7MB.

**Comment by flexiondotorg** [comment]
Qemu maximum supported screen resolution is 4 megapixels (2560x1600). Maximum number of heads is 4.

So,allocating more VRAM isn't going to enae 4K.
