### ISSUE TITLE
how to get qemu-virgil snap to recognize samba?

### ISSUE THREAD

**Issue by SteveDevOps** [wimpysworld/quickemu#5]
Martin, first off.. thx much for your latest changes! I am up and running now..

I'm having a remaining prob with samba and I'm new to snaps in general. How do I get qemu-virgil to recognize my samba smbd service so that my own snap install ends up with a /snap/qemu-virgil/current/usr/sbin/smbd  ??

To be more specific.. this condtion isn't being met:
if [ "${ENGINE}" == "virgil" ] && [ **-e /snap/qemu-virgil/current/usr/sbin/smbd** ]; then

thx!

**Comment by flexiondotorg** [comment]
I've been making changes to `qemu-virgil`, see this PR which has just been merged:

  * https://github.com/ogra1/qemu-virgil-snap/pull/4

The commit that adds `smbd` is here:

  * https://github.com/ogra1/qemu-virgil-snap/pull/4/commits/f3bcebf40d082873bca1d37429e4d20c2afdaf00

I'll close this since my changes are merged and a new `qemu-virgil` will land soon :smiley:
