### ISSUE TITLE
[Documentation] Expand the disk space after qemu disk creation

### ISSUE THREAD

**Issue by bigdiff** [wimpysworld/quickemu#564]
#### Expected behaviour

I've created many VMs with 15~20GB disk space, but after a while of updating them I'm running out of space. Is there a guide I can follow to expand the disk without having to do the whole thing over. I've tried `qemu-img resize` but the disk used by the VM still remains the same size, that only adds free space at the end and does not add to the root partition. 

#### Actual behaviour

I'm running out of space frequently.

#### Steps to reproduce the behaviour

- install a VM of ubuntu
- after updating the kernel and installing a browser
- there is no space left

#### Quickemu output

`quickemu v4.3`

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
Ubuntu 22.04
```

**Comment by philclifford** [comment]
In order to use the extra space you need to use the relevant guest OS tools to extend the relevant disk partition into the free space, then extent the filesystem. Just what is required depends on the guest OS and on how you chose to use the virtual disk in the installation. In a simple Linux case that might be to use gparted to resize the root partition then use resize2fs to grow the filesystem into the space. If you used lvm then you'll need to ensure the PV picked up the new size, extend the lvol then grow the filesystem. And so on...
You may wish to copy the disk image and work on that copy, check the integrity at the start and each stage (qemu-img and fsck etc.) and you might find it easier if you can boot a relevant live system VM to work on the disk image (just to reduce the need for reboots and complications of resizing a mounted and in-use filesystem, but these days it isn't always essential.

**Comment by philclifford** [comment]
You might also look at general space usage hygiene as 15-20Gb should be ample for what you describe: you can find a lot of space can be recovered by ensuring you apt-get autoremove to get rid of replaced kernels, and by purging old snap versions that have been updated.

**Comment by philclifford** [comment]
Some useful reading on resizing root  (and do read all the comments!)

https://askubuntu.com/questions/24027/how-can-i-resize-an-ext-root-partition-at-runtime
https://dade2.net/kb/how-to-extend-filesystem-on-linux/
