### ISSUE TITLE
Add machine readable output of support operating systems and releases to quickget

### ISSUE THREAD

**Issue by flexiondotorg** [wimpysworld/quickemu#97]
A few people have shown some interest in creating a GUI frontend for `quickget` and `quickemu`, this should help those developers.

@marxjohnson @frenchguych I'm interested to hear what you might find useful.

**Comment by ymauray** [comment]
I agree with Mark.

The JSON should also return a "pretty name" , so we could present that in our tools. "openSUSE" is correct, "Opensuse" is not :-) 

That pretty name could be presented to the command line too, but not on initial release, otherwise our tools will break.

And while we're at it, maybe we can throw a logo in there, too, but that would be a "nice to have".

I'm going to give that a go, it nobody objects.

Marc, did you have a format in mind already for the json ? Should we take that discussion to Telegram ?
